spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://bitpicklejua.cvefgsjhj6vl.ap-northeast-2.rds.amazonaws.com:3306/bitpicklejua
    username: bitpicklejua
    password: bitpicklejua
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    database : mysql
    hibernate:
     format_sql: true
     ddl-auto: update


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


server:
  port: 8080